// Monitor 1 - Network Focused - View Configuration
export const viewsConfig = {
 

 home: {
    id: 'home',
    label: 'Overview & Menu',
    badge: null,
    title: 'Network Focused',
    tag: 'Overview',
    pillText: 'LIVE TRAINING NETWORK',
    video: {
      src: 'videos/NF-V.mp4',
      poster: 'Images/NF-V.jpg'
    },
    panel: {
      title: "GLOBAL NETWORKS. NON‑TERRESTRIAL READY. EXPEDITIONARY BY DESIGN",

      listItems: [
          'Athena‑Tek delivers resilient, multi‑bearer network architectures purpose‑built for Live Training and Test & Evaluation across the world’s most challenging environments. Our Network Focused pillar ensures that soldier systems, EXCON, vehicles, sensors, cameras, and data collectors remain connected under any condition—urban, rural, mountainous, maritime, or Indo‑Pacific island terrain.'


      ],
      footer: {
        text: 'After this overview, visitors are ready for',
        links: ['Monitor 2 – TED', 'Monitor 3 – Solution Driven']
      }
    },
    isHome: true
  },

  training: {
    id: 'training',
    label: 'Training Area Challenge',
    badge: 'Scenario',
    title: 'Training Area Challenge',
    tag: 'Terrain & LOS',
    pillText: 'TERRAIN OCCLUSION',
    image: {
      src: 'Images/NF-TAC.png',
      alt: 'Terrain occlusion and line-of-sight challenges'
    },
    panel: {
      title: 'Why the Network Struggles', 
      description: "Army training areas are huge, complex environments. Ranges can span tens of kilometers, with hills, forests, and dense urban training villages. Traditional comms were never designed to move high-fidelity training data, sensor fusion outputs, and AI models all at once. Athena-Tek starts by fixing the network foundation.",
      listItems: [
        'Occluding terrain causes network dead zones.',
        'MOUT sites break connectivity inside buildings.',
        "Legacy networks weren't built for AI-rich data flows."
      ],
      footer: {
        text: 'The next view shows how Athena-Tek overlays a resilient mesh and 5G layer onto this environment.'
      }
    }
  },

  mesh: {
    id: 'mesh',
    label: 'Expeditionary 5G + Mesh',
    badge: 'Architecture',
    title: 'Expeditionary 5G + Mesh',
    tag: 'Hybrid Fabric',
    pillText: '5G / LTE / 900 MHz',
    image: {
      src: 'Images/NF-Ex.png',
      alt: 'Expeditionary 5G and mesh network diagram'
    },
    panel: {
      title: 'Self-Healing Connectivity',
      description: 'Athena-Tek deploys a hybrid 5G, LTE, and 900 megahertz mesh fabric. Vehicle nodes, portable masts, and TED devices form a self-healing network across the training area. We don’t require heavy new infrastructure – we layer on top of what the Army already has, then extend coverage with expeditionary mesh nodes wherever the training scenario demands',
      listItems: [
        'Non-Terrestrial Network (NTN)',
        '5 Watt 900 MHz Mesh – 2 km per hop',
        '5G / 4G where available',
        'Zero-install expeditionary nodes'
      ],
      footer: {
        text: 'This network carries the sensor fusion and RTCA data generated by TED.'
      }
    }
  },

  starlink: {
    id: 'starlink',
    label: 'Starlink & Range Systems',
    badge: 'Backhaul',
    title: 'Starlink & Range Systems',
    tag: 'Reachback',
    pillText: 'TAK / LTEC / STE',
    image: {
      src: 'Images/NF-Star.png',
      alt: 'Starlink backhaul to TAK/LTEC server'
    },
    panel: {
      title: 'From Edge Nodes to Range Control',
      description: 'Because TED speaks standards-based IP, any mesh node or vehicle can act as a gateway to Starlink or other tactical SATCOM. From there, data flows directly into existing TAK servers and EXCON at the command post. The result is a unified network that supports STE Live Training concepts – from e-bullet adjudication to AI-enabled After-Action Reviews',
      listItems: [
        'Standards-based IP',
        'Supports STE Live Training and future expansion.',
        'TAK, EXCON'
      ],
      footer: {
        text: 'From here, visitors should continue at',
        links: ['Monitor 2 – TED', 'Monitor 3 – Solution Driven']
      }
    }
  },

  videoMulti5G: {
    id: 'videoMulti5G',
    label: 'Video: Multi 5G MAPs',
    badge: 'Video',
    title: 'Multi 5G MAPs',
    tag: 'Video Demo',
    pillText: 'VIDEO',
    video: {
      src: 'videos/Multi5GMAPs.mp4',
      poster: 'Images/NF-Ex.png'
    },
    panel: {
      title: '',
      description: '',
      listItems: [],
      footer: {
        text: ''
      }
    }
  },

  videoSingleMAP: {
    id: 'videoSingleMAP',
    label: 'Video: Single MAP 28',
    badge: 'Video',
    title: 'Single MAP 28',
    tag: 'Video Demo',
    pillText: 'VIDEO',
    video: {
      src: 'videos/SingleMAP28.mp4',
      poster: 'Images/NF-Star.png'
    },
    panel: {
      title: '',
      description: '',
      listItems: [],
      footer: {
        text: ''
      }
    }
  }
};

export const siteConfig = {
  title: 'Athena-Tek | Monitor 1 – Network Focused',
  sidebar: {
    title: 'Network Focused',
    subtitle: 'Expeditionary connectivity for next-generation live training.',
    menuLabel: 'Select View',
    footerTip: 'Tip: Explore each view here, then move to the TED and Solution Driven monitors to see how it all connects.'
  },
  defaultView: 'home'
};
