// Monitor 1 - Network Focused - View Configuration
export const viewsConfig = {
  home: {
    id: 'home',
    label: 'Overview & Menu',
    badge: null,
    title: 'Network Focused',
    tag: 'Overview',
    pillText: 'LIVE TRAINING NETWORK',
    image: {
      src: 'Images/NF-1G.jpg',
      alt: 'Network Focused overview artwork'
    },
    panel: {

      listItems: [
        'Visualizes training area challenges and dead zones.',
        'Shows how 5G, LTE, and 900 MHz mesh work together.',
        'Explains Starlink / SATCOM reachback into TAK & LTEC.'
      ],
      footer: {
        text: 'After this overview, visitors are ready for',
        links: ['Monitor 2 – TED', 'Monitor 3 – Solution Driven']
      }
    },
    isHome: true
  },

  training: {
    id: 'training',
    label: 'Training Area Challenge',
    badge: 'Scenario',
    title: 'Training Area Challenge',
    tag: 'Terrain & LOS',
    pillText: 'TERRAIN OCCLUSION',
    image: {
      src: 'm1_training_area_challenge.png',
      alt: 'Terrain occlusion and line-of-sight challenges'
    },
    panel: {
      title: 'Why the Network Struggles',
      description: "Real ranges aren't open fields. Hills, forests and urban structures block line-of-sight radios, creating blind spots just when commanders need data most.",
      listItems: [
        'Occluding terrain causes network dead zones.',
        'MOUT sites break connectivity inside buildings.',
        "Legacy networks weren't built for AI-rich data flows."
      ],
      footer: {
        text: 'The next view shows how Athena-Tek overlays a resilient mesh and 5G layer onto this environment.'
      }
    }
  },

  mesh: {
    id: 'mesh',
    label: 'Expeditionary 5G + Mesh',
    badge: 'Architecture',
    title: 'Expeditionary 5G + Mesh',
    tag: 'Hybrid Fabric',
    pillText: '5G / LTE / 900 MHz',
    image: {
      src: 'm1_expeditionary_5g_mesh.png',
      alt: 'Expeditionary 5G and mesh network diagram'
    },
    panel: {
      title: 'Self-Healing Connectivity',
      description: 'Athena-Tek uses 5G and LTE where infrastructure exists, then extends coverage with 5 W 900 MHz mesh nodes on vehicles, masts, and TEDs.',
      listItems: [
        'Self-healing mesh fabric across the training box.',
        '~2 km per hop with 5 W 900 MHz mesh.',
        'No heavy permanent infrastructure required.'
      ],
      footer: {
        text: 'This network carries the sensor fusion and RTCA data generated by TED.'
      }
    }
  },

  starlink: {
    id: 'starlink',
    label: 'Starlink & Range Systems',
    badge: 'Backhaul',
    title: 'Starlink & Range Systems',
    tag: 'Reachback',
    pillText: 'TAK / LTEC / STE',
    image: {
      src: 'm1_starlink_range_systems.png',
      alt: 'Starlink backhaul to TAK/LTEC server'
    },
    panel: {
      title: 'From Edge Nodes to Range Control',
      description: 'With standards-based IP, any mesh node can backhaul via Starlink or tactical SATCOM, delivering live data into TAK and LTEC services.',
      listItems: [
        'Starlink links the training area to range control.',
        'Supports STE Live Training and future expansion.',
        'Delivers eBullet, RTCA, and AAR data in near real time.'
      ],
      footer: {
        text: 'From here, visitors should continue at',
        links: ['Monitor 2 – TED', 'Monitor 3 – Solution Driven']
      }
    }
  }
};

export const siteConfig = {
  title: 'Athena-Tek | Monitor 1 – Network Focused',
  sidebar: {
    title: 'Network Focused',
    subtitle: 'Expeditionary connectivity for next-generation live training.',
    menuLabel: 'Select View',
    footerTip: 'Tip: Explore each view here, then move to the TED and Solution Driven monitors to see how it all connects.'
  },
  defaultView: 'home'
};
